name: Validate Transforms

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download validator_cli
        run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r tests/requirements.txt;

      - name: Run tests
        run: cd tests; pytest test-*.py -vv
